apiVersion: v1
kind: Service
metadata:
  
  name: painel-dev 
  
spec:
  type: NodePort
  selector:
    app: app-tools
    role: master
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 

