apiVersion: apps/v1
kind: Deployment 
metadata:
  name: app-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-tools
  spec:
      containers:
      - name: app-tools
        image: celsinhobueno/painel:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 5m
            memory: 85Mi        