apiVersion: v1
kind: Deployment 
metadata:
  namespace: default
  name: app-tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-tools
  spec:
      containers:
      - name: app-tools
        image: celsinhobueno/painel:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 5m
            memory: 85Mi
  contexts:
    - context:
      name: do-nyc3-k8s-1-26-3-do-0-nyc3-1681435794472